### ISSUE TITLE
update rest generator to swagger codegen v3 with OpenAPI 3 support

### ISSUE THREAD

**Issue by BelAn97** [jdi-testing/jdi-dark-generator#16]
https://github.com/swagger-api/swagger-codegen/releases/tag/v3.0.20

**Comment by macieklukasik88** [comment]
ISSUE:
As of today, the generator does not support API specification JSON file in Open API v3 format.

STEPS TO REPRODUCE:

When I am trying to generate code from open API v.3.0.0 JSON file I am getting the following error:

`$ java -jar jdi-dark-rest-generator/target/DarkGenerator.jar generate -i openapi.json
[main] INFO io.swagger.parser.Swagger20Parser - reading from openapi.json
[main] INFO io.swagger.parser.Swagger20Parser - reading from openapi.json
Exception in thread "main" java.lang.**RuntimeException: The swagger specification supplied was not valid**
        at com.epam.jdi.generator.CodegenConfigurator.build(CodegenConfigurator.java:228)
        at com.epam.jdi.generator.Generate.run(Generate.java:121)
        at com.epam.jdi.generator.SwaggerCodegenJDI.main(SwaggerCodegenJDI.java:15)
`
(POSSIBLE) WORKAROUND:

In API specification JSON file replace:
`"openapi": "3.0.0"`
with:
`"swagger":"2.0"`

That makes the generator works ut not sure if generated code will be 100% usable.
